name: Build and test Go
on: [push, pull_request]
jobs: 
  build: 
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "Set up Go 1.13"
        uses: actions/setup-go@v1
        with: 
          go-version: 1.13
      - 
        name: "Check out source code"
        uses: actions/checkout@v2
      - 
        env: 
          GOPROXY: "https://proxy.golang.org"
        name: Install dependencies
        run: |
          go get -u github.com/gin-gonic/gin          
      -         
        name: Static Code Check
        run: |
          export PATH=${PATH}:`go env GOPATH`/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck .
      - 
        env: 
          GOPROXY: "https://proxy.golang.org"
        name: Build
        run: "go build ."
      - 
        env: 
          GOPROXY: "https://proxy.golang.org"
        name: Test
        run: "go test -v ."
      - 
        name: Containerize
        run: "go test -v ."
      - 
        name: Deploy to K8
        run: "go test -v ."
        